#!/usr/bin/env python3
"""Synthesise the new-message pop and emit src/pop_wav.h.

Jake asked for "a classic facebook pop notification sound". This does NOT copy
Facebook's sound file - that one is theirs. It builds a pop from scratch in the
same spirit, so the result is ours to ship.

    python tools/make_pop.py          # writes tools/pop.wav and src/pop_wav.h

Tuning, if it wants to be different:
  F_HI / F_LO   how bright it starts and how round it lands
  GLIDE         how fast the pitch falls (smaller = snappier "pop")
  DECAY         how long it rings (bigger = more "bloop")
Keep the tail fade: a buffer that stops at non-zero amplitude clicks the speaker.
"""
import math
import os
import struct

SR = 16000       # sample rate. The I2S output resamples anything, but small = less flash.
DUR = 0.115      # seconds
F_HI = 1400.0    # starting pitch, Hz
F_LO = 520.0     # landing pitch, Hz
GLIDE = 0.018    # pitch-fall time constant, seconds
ATTACK = 0.0018  # fade-in, seconds. Shorter than this and it clicks.
DECAY = 0.032    # amplitude decay time constant, seconds
HARM = 0.30      # second-harmonic amount on the leading edge (the bright "p")
HARM_T = 0.006   # how fast that harmonic dies away
TAIL = 0.003     # fade-out at the very end, seconds
PEAK_DBFS = -1.5

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)


def render():
    n = int(SR * DUR)
    phase = 0.0
    vals = []
    for i in range(n):
        t = i / SR
        # Integrate the frequency to get phase. Multiplying instead (sin(2*pi*f*t))
        # is the classic sweep bug: it gives the wrong instantaneous pitch.
        f = F_LO + (F_HI - F_LO) * math.exp(-t / GLIDE)
        phase += 2.0 * math.pi * f / SR
        body = math.sin(phase) + HARM * math.exp(-t / HARM_T) * math.sin(2.0 * phase)
        vals.append(body * min(1.0, t / ATTACK) * math.exp(-t / DECAY))

    peak = max(abs(v) for v in vals) or 1.0
    target = 10 ** (PEAK_DBFS / 20.0)
    tail = int(SR * TAIL)
    pcm = bytearray()
    for i, v in enumerate(vals):
        s = v / peak * target
        if i >= n - tail:      # land on silence
            s *= (n - i) / tail
        pcm += struct.pack("<h", max(-32767, min(32767, int(s * 32767))))
    return bytes(pcm)


def wav(pcm):
    return (b"RIFF" + struct.pack("<I", 36 + len(pcm)) + b"WAVEfmt " +
            struct.pack("<IHHIIHH", 16, 1, 1, SR, SR * 2, 2, 16) +
            b"data" + struct.pack("<I", len(pcm)) + pcm)


def header(data):
    out = ['// -----------------------------------------------------------------------------',
           '// The new-message "pop", as a 16 kHz mono 16-bit WAV in flash.',
           '//',
           '// GENERATED by tools/make_pop.py - edit that, not this.',
           '// -----------------------------------------------------------------------------',
           '#pragma once', '#include <cstdint>', '#include <pgmspace.h>', '',
           'const uint8_t kPopWav[] PROGMEM = {']
    for i in range(0, len(data), 16):
        out.append('    ' + ', '.join('0x%02x' % b for b in data[i:i + 16]) + ',')
    out += ['};', 'const uint32_t kPopWavLen = sizeof(kPopWav);', '']
    return '\n'.join(out)


if __name__ == "__main__":
    data = wav(render())
    with open(os.path.join(HERE, "pop.wav"), "wb") as f:
        f.write(data)
    with open(os.path.join(ROOT, "src", "pop_wav.h"), "w", newline="\n") as f:
        f.write(header(data))
    print("wrote tools/pop.wav and src/pop_wav.h (%d bytes of WAV)" % len(data))
